// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Ahmet Can Ceylan"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/metrics": {
            "get": {
                "description": "Get current status of queues and system health.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Observability"
                ],
                "summary": "System Metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications": {
            "get": {
                "description": "Retrieves notifications with filtering and pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "List notifications",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by channel",
                        "name": "channel",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Limit for pagination",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_ahmetcanc_notify-one_internal_domain.Notification"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new notification and sends it.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Send single notification",
                "parameters": [
                    {
                        "description": "Notification details",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ahmetcanc_notify-one_internal_domain.Notification"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Returns notification ID and status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/notifications/batch": {
            "post": {
                "description": "Creates multiple notifications in a single request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Send batch notifications",
                "parameters": [
                    {
                        "description": "List of notifications",
                        "name": "notifications",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_ahmetcanc_notify-one_internal_domain.Notification"
                            }
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/batch/{batchId}/cancel": {
            "patch": {
                "description": "Cancels all pending notifications in a batch.",
                "tags": [
                    "Notifications"
                ],
                "summary": "Cancel batch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Batch ID",
                        "name": "batchId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_ahmetcanc_notify-one_internal_domain.Notification": {
            "type": "object",
            "properties": {
                "batch_id": {
                    "type": "string"
                },
                "channel": {
                    "$ref": "#/definitions/github_com_ahmetcanc_notify-one_internal_domain.NotificationChannel"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "idempotency_key": {
                    "type": "string"
                },
                "next_retry_at": {
                    "type": "string"
                },
                "priority": {
                    "$ref": "#/definitions/github_com_ahmetcanc_notify-one_internal_domain.NotificationPriority"
                },
                "recipient": {
                    "type": "string"
                },
                "retry_count": {
                    "type": "integer"
                },
                "scheduled_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_ahmetcanc_notify-one_internal_domain.NotificationStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_ahmetcanc_notify-one_internal_domain.NotificationChannel": {
            "type": "string",
            "enum": [
                "sms",
                "email",
                "push"
            ],
            "x-enum-varnames": [
                "ChannelSMS",
                "ChannelEmail",
                "ChannelPush"
            ]
        },
        "github_com_ahmetcanc_notify-one_internal_domain.NotificationPriority": {
            "type": "string",
            "enum": [
                "low",
                "normal",
                "high"
            ],
            "x-enum-varnames": [
                "PriorityLow",
                "PriorityNormal",
                "PriorityHigh"
            ]
        },
        "github_com_ahmetcanc_notify-one_internal_domain.NotificationStatus": {
            "type": "string",
            "enum": [
                "pending",
                "processing",
                "sent",
                "failed",
                "cancelled"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusProcessing",
                "StatusSent",
                "StatusFailed",
                "StatusCancelled"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3333",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "NotifyOne API",
	Description:      "High-performance, scalable notification service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
